name: CI/CD
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/../Sudoku
            git pull
      - name: build
        run: yarn build;
      - name: copy
        uses: appleboy/ssh-action
        with:
          script: |
            rm -r ../var/www/ariqun_ru/data/www/ariqun.ru/*
            mv build/* ../var/www/ariqun_ru/data/www/ariqun.ru/